
[package]
name = "ic10emu_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
ic10emu = { path = "../ic10emu" }
console_error_panic_hook = "0.1.7"
js-sys = "0.3.69"
web-sys = { version = "0.3.69", features = ["WritableStream", "console"] }
wasm-bindgen = "0.2.81"
wasm-bindgen-futures = { version = "0.4.30", features = [
  "futures-core-03-stream",
] }
wasm-streams = "0.3"

[lib]
crate-type = ["cdylib", "rlib"]
[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
